<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0gdbwxc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0gdbwxc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0gdbwxc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0gdbwxc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0gdbwxc\appProdProjectContainer(array(
    'container.build_hash' => '0gdbwxc',
    'container.build_id' => '7a769286',
    'container.build_time' => 1519052850,
));
