<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV74zlxv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV74zlxv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV74zlxv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV74zlxv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV74zlxv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'V74zlxv',
    'container.build_id' => '0c9d80d3',
    'container.build_time' => 1519314201,
));
